### ISSUE TITLE
Maybe add a Photo of the editor In readme.md

### ISSUE THREAD

**Issue by Siddhesh2377** [TS-Code-Editor/AndroidAppStudio#2]

**Comment by devkumar00001** [comment]
![Screenshot_2024-03-30-09-48-41-301_com tscodeeditor android appstudio](https://github.com/TS-Code-Editor/AndroidAppStudio/assets/96680248/43568528-dd4e-480a-a24f-94762977d91e)
![Screenshot_2024-03-30-09-48-48-607_com tscodeeditor android appstudio](https://github.com/TS-Code-Editor/AndroidAppStudio/assets/96680248/760f8adc-cdbb-43ff-a7db-d8b0ad5cc7e5)
![Screenshot_2024-03-30-09-48-59-108_com tscodeeditor android appstudio](https://github.com/TS-Code-Editor/AndroidAppStudio/assets/96680248/9d226b0d-b60f-4af5-b058-28a96f45e609)
![Screenshot_2024-03-30-09-49-06-144_com tscodeeditor android appstudio](https://github.com/TS-Code-Editor/AndroidAppStudio/assets/96680248/64883c68-28e3-476f-95e2-8ce99870c53f)
![Screenshot_2024-03-30-09-49-25-043_com tscodeeditor android appstudio](https://github.com/TS-Code-Editor/AndroidAppStudio/assets/96680248/7b2014d8-c070-4322-9229-f3eb95b5c7a6)

Here you can see screenshot of app.

Note: I will not add screenshot of app in readme file until we add Java file manager with block interface.

**Comment by Siddhesh2377** [comment]
Ok, thankyou

**Comment by DevAnDroidCoder** [comment]
Added screenshots
